[package]
name = "async-lisp"
version = "0.1.0"
authors = ["Syed Faraaz Ahmad <faraaz98@live.com>"]
edition = "2019"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
